### ISSUE TITLE
Make the API public

### ISSUE THREAD

**Issue by ericboucher** [aqualinkorg/aqualink-app#504]
- Add a domain in front of the API and make it public (eg. api.aqualink.org)
- Expose documentation and examples (eg. using swagger)

**Comment by avalmas-programize** [comment]
I think the backend url is already public since it is running on a separate instance from the frontend
So all we need is the api documentation

**Comment by avalmas-programize** [comment]
Swagger is throwing the following error when executing POST /reefs (Register new site)
```
[Nest] 70811   - 03/30/2021, 7:24:22 PM   [ExceptionsHandler] XMLHttpRequest is not defined +8ms
ReferenceError: XMLHttpRequest is not defined
    at /home/antonios/Documents/Programize/aqualink-app-backend/node_modules/swagger-ui-dist/swagger-ui-bundle.js:2:898340
    at new Promise (<anonymous>)
    at E (/home/antonios/Documents/Programize/aqualink-app-backend/node_modules/swagger-ui-dist/swagger-ui-bundle.js:2:898207)
    at u.blockSize [as retrievalFunction] (/home/antonios/Documents/Programize/aqualink-app-backend/node_modules/geotiff/dist-node/geotiff.js:32:2459)
    at u.requestData (/home/antonios/Documents/Programize/aqualink-app-backend/node_modules/geotiff/dist-node/geotiff.js:32:2218)
    at u.fetch (/home/antonios/Documents/Programize/aqualink-app-backend/node_modules/geotiff/dist-node/geotiff.js:32:1616)
    at async Function.fromSource (/home/antonios/Documents/Programize/aqualink-app-backend/node_modules/geotiff/dist-node/geotiff.js:40:7332)
```

The issue is arising after the call of the `getMMM` function in the `temperature.ts` file:
```ts
export async function getMMM(long: number, lat: number) {
  const tiff = await GeoTIFF.fromUrl(`${MonthlyMaxRoot}sst_clim_mmm.tiff`);     <========
  return getValueFromTiff(tiff, long, lat);
}
```

The issue seems to start from the below module
https://geotiffjs.github.io/geotiff.js/source_remote.js.html#line185
